# Generated by Django 3.1.7 on 2021-09-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('numTel', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('dateEntree', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée de l'enseignant")),
                ('dateSortie', models.DateTimeField(null=True)),
                ('role', models.CharField(max_length=60)),
                
            ],
        ),
        migrations.CreateModel(
            name='EnsFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RespoFiliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('numTel', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('dateNaiss', models.DateField()),
                ('lieuNaiss', models.CharField(max_length=60)),
                ('dateEntree', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée de l'étudiant")),
                ('dateSortie', models.DateTimeField(null=True)),
                ('delegue', models.BooleanField(default=False)),
                ('codePermanent', models.IntegerField()),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFiliere', models.CharField(max_length=60)),
                ('RespoFiliere', models.ManyToManyField(through='inscrire.EnsFiliere', to='inscrire.Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Modalite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraisInscription', models.IntegerField()),
                ('mensualite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RespoScolarite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('numTel', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomNiveau', models.CharField(max_length=60)),
                ('numNiveau', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='ModFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.filiere')),
                ('modalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.modalite')),
            ],
        ),
        migrations.AddField(
            model_name='modalite',
            name='filiere',
            field=models.ManyToManyField(through='inscrire.ModFiliere', to='inscrire.Filiere'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeScolaire', models.CharField(max_length=60)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.filiere')),
                ('respoScolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.resposcolarite')),
            ],
        ),
        migrations.AddField(
            model_name='ensfiliere',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.filiere'),
        ),
        migrations.CreateModel(
            name='Ec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeEc', models.CharField(max_length=60)),
                ('nomEc', models.CharField(max_length=60)),
                ('presentation', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.enseignant')),
            ],
        ),
    ]
